# URL de conexión a PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d0kv6d3uibrs739smlro-a:5432/todotechdb

# Usuario y contraseña
spring.datasource.username=todouser
spring.datasource.password=sLL42mWBQe3tMhLlel3sGJN2qwx2181q

# Driver JDBC para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL generado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para que Hibernate cree/actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Ejecutar data.sql después de crear tablas (si lo usas)
spring.jpa.defer-datasource-initialization=true
