# PostgreSQL DB config (Render)
spring.datasource.url=jdbc:postgresql://dpg-d019o8ggjchc73et68rg-a.oregon-postgres.render.com:5432/todotechbd?sslmode=require
spring.datasource.username=todotechbd_user
spring.datasource.password=KjI0OjxVA0GMd9D68SZ5iNiPn1rUOcd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Server - Configuración del puerto para el backend
server.port=${PORT:8080}

# Configuraciones adicionales recomendadas
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuración de conexión a la base de datos
spring.datasource.hikari.connection-timeout=20000


# Configuración para manejo de errores
spring.jpa.properties.hibernate.check_nullability=true


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2